local map = vim.keymap.set
--map qwertz
map("n", "ö", ":")
map("v", "ö", ":")
map("o", "ö", ":")
map("n", "<C-ü>", "[")
map("n", "<C-+>", "]")
map("v", "<C-ü>", "[")
map("v", "<C-+>", "]")
map("n", "<C-S-ü>", "{")
map("n", "<C-S-+>", "}")
map("v", "<C-S-ü>", "{")
map("v", "<C-S-+>", "}")
map("n", "<C-^>", "`")
map("n", "<C-°>", "~")
